### ISSUE TITLE
Provider: Checkout 

### ISSUE THREAD

**Issue by DanDrix8391** [MyOwnGamesLLC/WebDjangular#14]
a checkout plan where you can build your own custom plans (Internet, TV and Telephone).

- [x] Select the Internet Plan
- [x] Select the Internet addon
- [x] Select the TV plan
- [x] Select the TV addons (E.G. HBO)
- [x] Select the Telephone plan
- [x] Select the Telephone addons

**Comment by PauloPeres** [comment]
Complete the Checkout With Promotion Logic
